export interface EventData {
  id: number;
  name: string;
  description: string;
  date: string;
  startTime: string;
  endTime: string;
  barId: number;
  barName: string;
  barLocation: string;
  barLat: number;
  barLng: number;
  dj?: string;
  genre?: string;
  price: number;
  ticketPrice?: number;
  image: string;
  images: string[];
  category: 'music' | 'party' | 'happy_hour' | 'live_show' | 'karaoke' | 'trivia' | 'sports' | 'networking' | 'special';
  tags: string[];
  capacity: number;
  attendees: number;
  interestedCount: number;
  goingCount: number;
  isTicketed: boolean;
  ticketUrl?: string;
  status: 'upcoming' | 'ongoing' | 'completed' | 'cancelled' | 'sold_out';
  ageRestriction?: string;
  dressCode?: string;
  socialMedia?: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
  };
  isPublic: boolean;
  canGuestsInviteFriends: boolean;
  hostMessage?: string;
  discussionEnabled: boolean;
  photosEnabled: boolean;
  lastUpdate?: string;
  views: number;
  shares: number;
  createdBy: string;
  coHosts?: string[];
  createdAt: string;
  updatedAt: string;
}
